import type { Company } from '../types';

export const MOCK_COMPANIES: Company[] = [
  {
    id: '1',
    name: 'Innovatech Solutions',
    domain: 'innovatech.com',
    description: 'A leading provider of cloud-based AI solutions for enterprise customers, focusing on automation and data analytics.',
    industry: 'Artificial Intelligence',
    funding_stage: 'Series C',
    hiring_signals: { roles: ['Machine Learning Engineer', 'Data Scientist', 'Cloud Architect'] },
    logo_url: 'https://picsum.photos/seed/innovatech/100',
  },
  {
    id: '2',
    name: 'QuantumLeap AI',
    domain: 'quantumleap.ai',
    description: 'Specializes in developing next-generation quantum computing algorithms to solve complex optimization problems.',
    industry: 'Quantum Computing',
    funding_stage: 'Series A',
    hiring_signals: { roles: ['Quantum Physicist', 'Research Scientist'] },
    logo_url: 'https://picsum.photos/seed/quantum/100',
  },
  {
    id: '3',
    name: 'BioGen Futures',
    domain: 'biogenfutures.com',
    description: 'A biotech firm using CRISPR technology for gene editing and developing novel therapies for genetic disorders.',
    industry: 'Biotechnology',
    funding_stage: 'Post-IPO',
    hiring_signals: null,
    logo_url: 'https://picsum.photos/seed/biogen/100',
  },
  {
    id: '4',
    name: 'Cybershield Inc.',
    domain: 'cybershield.io',
    description: 'Provides comprehensive cybersecurity services, including threat detection, incident response, and security consulting.',
    industry: 'Cybersecurity',
    funding_stage: 'Seed',
    hiring_signals: { roles: ['Security Analyst', 'Penetration Tester', 'DevSecOps Engineer'] },
    logo_url: 'https://picsum.photos/seed/cyber/100',
  },
  {
    id: '5',
    name: 'GreenShift Energy',
    domain: 'greenshift.energy',
    description: 'Develops and manufactures innovative solar panels and energy storage solutions for residential and commercial use.',
    industry: 'Renewable Energy',
    funding_stage: 'Series B',
    hiring_signals: { roles: ['Electrical Engineer', 'Sales Director'] },
    logo_url: 'https://picsum.photos/seed/green/100',
  },
  {
    id: '6',
    name: 'SquarePeg',
    domain: 'squarepeghires.com',
    description: 'A data-driven hiring platform that matches candidates to jobs based on their real-world qualifications and potential, not just keywords.',
    industry: 'Human Resources Tech',
    funding_stage: 'Series A',
    hiring_signals: { roles: ['Full-Stack Developer', 'Product Manager'] },
    logo_url: 'https://picsum.photos/seed/squarepeg/100',
  },
  {
    id: '7',
    name: 'Rocketship.ai',
    domain: 'rocketship.ai',
    description: 'An AI-powered platform for sourcing and engaging top talent globally, specializing in remote-first companies.',
    industry: 'Recruitment AI',
    funding_stage: 'Seed',
    hiring_signals: { roles: ['AI Researcher', 'Sales Development Representative'] },
    logo_url: 'https://picsum.photos/seed/rocketship/100',
  },
  {
    id: '8',
    name: 'Built In',
    domain: 'builtin.com',
    description: 'An online community for startups and tech companies, offering job listings, industry news, and events across major tech hubs.',
    industry: 'Tech Media & Recruiting',
    funding_stage: 'Private Equity',
    hiring_signals: null,
    logo_url: 'https://picsum.photos/seed/builtin/100',
  },
  {
    id: '9',
    name: 'BrainTrust',
    domain: 'braintrust.com',
    description: 'A decentralized talent network that connects skilled, vetted knowledge workers with the world’s leading companies.',
    industry: 'Web3 & Freelance Platform',
    funding_stage: 'Token Launch',
    hiring_signals: { roles: ['Solidity Developer', 'Community Manager'] },
    logo_url: 'https://picsum.photos/seed/braintrust/100',
  },
  {
    id: '10',
    name: 'Wellfound',
    domain: 'wellfound.com',
    description: 'Formerly AngelList Talent, it is the world’s largest startup network, helping startups hire and job-seekers find their next role.',
    industry: 'Startup Recruiting',
    funding_stage: 'Acquired',
    hiring_signals: { roles: ['Startup Scout', 'Marketing Lead'] },
    logo_url: 'https://picsum.photos/seed/wellfound/100',
  },
  {
    id: '11',
    name: 'Loom',
    domain: 'loom.com',
    description: 'A video messaging tool that helps you get your message across through instantly shareable videos, used extensively in remote work.',
    industry: 'SaaS / Enterprise Software',
    funding_stage: 'Acquired',
    hiring_signals: { roles: ['Senior Software Engineer', 'Customer Success Manager'] },
    logo_url: 'https://picsum.photos/seed/loom/100',
  },
  {
    id: '12',
    name: 'Cutshort',
    domain: 'cutshort.io',
    description: 'An AI-powered recruiting platform that uses matchmaking algorithms to connect tech professionals with relevant job opportunities.',
    industry: 'Human Resources Tech',
    funding_stage: 'Venture Capital',
    hiring_signals: { roles: ['Data Analyst', 'UX Designer'] },
    logo_url: 'https://picsum.photos/seed/cutshort/100',
  },
  {
    id: '13',
    name: 'Mercor',
    domain: 'mercor.com',
    description: 'A platform for hiring vetted, remote developers from a global talent pool, streamlining the international hiring process.',
    industry: 'Global Workforce',
    funding_stage: 'Seed',
    hiring_signals: { roles: ['Technical Recruiter', 'Client Partner'] },
    logo_url: 'https://picsum.photos/seed/mercor/100',
  },
  {
    id: '14',
    name: 'Landing.ai',
    domain: 'landing.ai',
    description: 'An industrial AI company that provides software and solutions to help manufacturers solve visual inspection problems.',
    industry: 'Industrial AI',
    funding_stage: 'Series A',
    hiring_signals: { roles: ['Computer Vision Engineer', 'Solutions Architect'] },
    logo_url: 'https://picsum.photos/seed/landingai/100',
  },
  {
    id: '15',
    name: 'Wefunder',
    domain: 'wefunder.com',
    description: 'A crowdfunding service that connects startups with investors online, democratizing access to venture capital.',
    industry: 'FinTech / Crowdfunding',
    funding_stage: 'Series A',
    hiring_signals: null,
    logo_url: 'https://picsum.photos/seed/wefunder/100',
  },
];
